// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"FaceControl","status":true,"description":"顔の向きでキャラクターを左右に動かすプラグインです（MediaPipe使用）","parameters":{}}
];
